Remove `Date` time_column from time series config template.
gretelai/gretel-blueprints pull request #154
Opened 2022-11-02 23:02 UTC by kboyd

## Problem
The time series config template previously assumed there was a `Date` column in the input data, with a comment to replace with your time column name. However, this led to frequent errors when the config template was not customized. 

## Solution
Comment out the `time_column` parameter, with instructions to uncomment and replace the name with the time column used in your own data.

Also added a link to the full documentation for the DGAN model, which contains more detailed info about all the configuration options.

2022-11-02 23:04 UTC, johntmyers requested changes
This needs to be a PR to develop. Also qq- what happens when the now commented out param is omitted and sent to our API?

2022-11-03 20:48 UTC, belson17 commented
> This needs to be a PR to develop. Also qq- what happens when the now commented out param is omitted and sent to our API?

Same question - what happens when there's no value for time_column, and has that been tested?

2022-11-03 22:35 UTC, kboyd commented
> This needs to be a PR to develop.

Fixed.

> Is not including the time_column equivalent to setting it to null?

Yes. Not including it will use the default value, which is null.

> Also qq- what happens when the now commented out param is omitted and sent to our API?
> Same question - what happens when there's no value for time_column, and has that been tested? The docs say:

If there's no value for `time_column`, we assume the input data is already sorted by time and there's no date/time column and proceed (e.g., with splitting into `max_sequence_len` chunks). This should work fine, but I just started a job from the dgan-oil notebook where I remove the `Date` column and the `time_column` param before submitting to confirm.

Unfortunately, what happens for the overall job with `time_column=null` will depend on the input data:

1. no column with dates/times - job uses all columns as the features as expected/intended and should succeed.
 
2. date/time column exists -  job assumes all columns are features, right now this will crash due to a string/object, after RDS-205, job should run and tries to learn and generate the date/time column as a categorical variable, this is unlikely to work well and will probably produce strange synthetic data for that column

With the current setup, there really isn't a one-size-fits-all config for dgan like we have for the tabular models. So there's not an ideal choice of `time_column` for this config. Maybe assuming no date/time column leads to fewer errors than assuming there's a date/time column **and** its name is `Date`, though maybe not.

We could address this with an additional dgan ticket where we add `time_column=auto` support that tries to autodetect a date/time column. Then use `auto` in this config template.

2022-11-03 23:18 UTC, kboyd commented
Test job worked with `time_column=null` and dropping the Date column for oil data. Model ran just fine and output is as expected.

2022-11-04 06:12 UTC, sami-t commented
Thanks Kendrick, looks good overall! A couple of suggestions:

1- What do you think about changing:

```
# If time series data contains a time column, uncomment
# and update with the column name.
```

To:

```
# If time series data contains a time column, uncomment
# and replace Date with the column name to be used for
# sorting. Otherwise DGAN will use the existing order.
```

It's a bit longer but hopefully a bit more clear for users.

2- If possible, I would suggest fixing RDS-205 and/or implementing `auto` for the `time_column` param before submitting this change. I worry that users who have been successful with the current config will use the latest blueprint without updating their data and fail. Of course depending on how long this might take, the potential benefit might be outweighed by new users failing because they don't have a new column...

2022-11-08 17:21 UTC, kboyd commented
Closing this PR. Will make a new one once `auto` is supported.

2022-11-08 17:21 UTC, closed without merging